apiVersion: v1
kind: Service
metadata:  
  name: go-service
spec:  
  selector:    
    role: app
  type: NodePort  
  ports:    
    - protocol: TCP
      port: 80      
      targetPort: 9000  
      nodePort: 32000 
  
