---
- hosts: webservers
  become: True
  tasks:
    - name: install pip
      apt:
        name: python-pip
        state: present
    
    - name: install pip3
      apt: name=python3-pip state=present 
    - name: Install Docker Module for Python
      pip:
        name: docker    
   
    - name: install docker
      apt:
        name: docker
        state: present
    - name: Add Docker key
      shell: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -

    - name: Add Docker repo
      shell: echo "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo $ID) $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

    - name: Install Docker
      apt:
        pkg: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker group is present
      group:
        name: docker
        state: present

    - name: Add current user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups:
          - docker
        append: yes
   
    - name: Create  container
      docker_container:
        name: nodeapp
        image: usko/golang:latest
        published_ports: ["8181:8181"]


